### PR TITLE
Upgrade to phpunit 6.4

### PR DESCRIPTION
**Pull request by jonny-no1**
> PHPUnit 5.7 is the old stable release series.
> It became stable on December 2, 2016.
> Support for PHPUnit 5 ends on February 2, 2018.
> — https://phpunit.de/

### CODE REVIEW

**Comment by jonny-no1** [comment]
[Build #35](https://travis-ci.org/kleijnweb/php-api-descriptions/jobs/301962241) executed 2 tests less than [build #32](https://travis-ci.org/kleijnweb/php-api-descriptions/jobs/232834559).

This is because of two data providers that were incorrectly annotated as tests:
- [JsonParserTest::yamlContentTypeProvider](https://github.com/kleijnweb/php-api-descriptions/blob/34732e510f4d7bccd5dadb3aefed11f828d52052/tests/Description/Document/Parser/JsonParserTest.php#L66)
- [YamlParserTest: yamlContentTypeProvider](https://github.com/kleijnweb/php-api-descriptions/blob/34732e510f4d7bccd5dadb3aefed11f828d52052/tests/Description/Document/Parser/YamlParserTest.php#L128)

**Comment by johnknl** [comment]
Thank you for the MR. I am not a fan of the style changes you made (although there is something to be said for invoking static methods, statically) so I applied the other changes manually to master. Thanks again.

**Comment by jonny-no1** [comment]
Thanks for your explanation! Below my response 😊

The interface changed in 6.4 – the methods used to be instance methods, now they’re static. So I changed the method calls. PHP isn’t strict enough to enforce the interface, but to me it’s still a breach of contract. Not just code style.

**Comment by johnknl** [comment]
Nope. The methods have been static for over 10 years. Don't take my word for it, check out this 11 year old class: https://github.com/sebastianbergmann/phpunit/blob/2.3/Framework/Assert.php

Over the course of those 10+ years, most people including myself have been using the instance invocation. The examples in PHPUnit use it (which is probably the main reason why everyone is doing it).

In other, non-PHPUnit code, I would not do this (breach of contract is a bit strong, but at the very least it is obfuscation). But for PHPUnit tests I don't see much harm and thus little reason to break with convention.

As far as the "test" method name prefix vs `@test` annotation, I simply prefer the method names read like BDD scenarios. The test prefix makes that a little awkward when read aloud. Also some features, specifically data providers have no other practical way of configuring, so what the hell, might as well use annotations to mark tests too.

None of this is a specifically hot button issue for me, I would much rather discuss design and features, but I hope this sheds some light on why didn't merge your PRs.

**Pull request closed without merging**
